url: 'https://shrishailsgajbhar.github.io'
baseurl: ''
title: Tech(B)log of Dr. Shrishail Gajbhar
permalink: '/post/:title'
google-analytics: UA-179063751-1
collections:
  ipcvmldl:
    output: true
    permalink: '/ipcvmldl/:title'

